version: '0.0.1'

services:
  frontend: 
    build: 
      context: ./frontend/finance_frontend
      dockerfile: Dockerfile 

    depends_on:
      - backend 

  backend: 
    build: 
      context: ./backend 
      dockerfile: Dockerfile 
    
  #   depends_on:
  #     - postgresql 

  # postgresql: 
  #   image: bitnami/postgresql
  #   volumes:
  #     - /Users/winson/Developer/personal_finance/backend:/bitnami/postgresql